### ISSUE TITLE
Quarto-related issue tracker

### ISSUE THREAD

**Issue by ravicodelabs** [datascijedi/website#115]
# Sections

- Instructions - How to use this issue tracker
- Issue Template - Copy/paste from here to "Open Issues" and edit to add an issue
- Open Issues - Add/update open issues here
- Closed Issues - Move any resolved issues here

# Instructions

This issue is being used to track the status of any issues that have a dependency on [Quarto](https://github.com/quarto-dev/quarto-cli), e.g. issues that require a modification be made to [Quarto](https://github.com/quarto-dev/quarto-cli). The tracker is open for anyone's input. Please feel free to edit this post directly to update the status of an issue, or add new such issues using the provided template. If you don't have write access to this post, feel free to leave a comment (so someone else can edit this post) or request access to edit directly. Thanks! 

---

# Issue Template

Please use (copy/paste) the below template for new issues:

### Status Checklist

- [ ] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [ ] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [ ] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [ ] If relevant, a temporary fix has been implemented. 
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [ ] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

# Open Issues

Add new issues here by editing this section. 

### Issue Details

The horizontal bar which separates the footer is missing on the "Activites" pages.

A fix for this was just added on the Quarto side: https://github.com/quarto-dev/quarto-cli/pull/4982, so we can switch over to this as soon as it is included in a release.

For now, PR https://github.com/datascijedi/website/pull/79 (merged) provides a temporary workaround.

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto fix: https://github.com/quarto-dev/quarto-cli/pull/4982
- DataSciJedi Temp fix: https://github.com/datascijedi/website/pull/79
- DataSciJedi issue: https://github.com/datascijedi/website/issues/78

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add links to any issue(s) above.)
- [x] The issue has been fixed on the Quarto side. (Add links to any PRs/commits above.)
- [x] If relevant, a temporary fix has been implemented. (Add links to any PRs/commits above.)
- [x] The fix has been included in a Quarto release or pre-release. 
- [x] The JEDI website was tested with the newer Quarto release or pre-release. 
- [x] We have updated the JEDI website to a newer Quarto release which includes the fixed issue. 
- [x] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Issue Details

Currently, Quarto couples its table of contents feature (toc) with its GitHub "Edit this page" feature. Since we don't always use a toc, there isn't a straightforward way for us to have the "Edit this page" link on each page. And, the placement of the "Edit this page" link is also restricted because of this coupling. 

As a workaround, we created a post-render script `render_scripts/github_link_insertion.ts` to insert the GitHub links. Once the Quarto project adds the appropriate functionality in, we can transition to a Quarto built-in solution rather than maintain the render script approach.

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/2142
- DataSciJedi issue: https://github.com/datascijedi/website/issues/35

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add links to any issue(s) above.)
- [ ] The issue has been fixed on the Quarto side. (Add links to any PRs/commits above.)
- [x] If relevant, a temporary fix has been implemented. (Add links to any PRs/commits above.)
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release which includes the fixed issue. 
- [ ] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Issue Details

The `netlify-plugin-quarto` plugin is meant to streamline the deploying of the website to Netlify, but is sometimes giving a GitHub API error. For the time being, a temporary fix is in place which just uses a shell script to download and install Quarto on the Netlify servers whenever deploying. 

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/netlify-plugin-quarto/issues/7

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [ ] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [x] If relevant, a temporary fix has been implemented. 
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [ ] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/5263
- Quarto fix: https://github.com/quarto-dev/quarto-cli/pull/5269

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [x] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [x] If relevant, a temporary fix has been implemented. 
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [x] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/7184

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [x] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [x] If relevant, a temporary fix has been implemented. 
- [x] The fix has been included in a Quarto release or pre-release. 
- [x] The JEDI website was tested with the newer Quarto release or pre-release. 
- [x] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [x] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Issue Details

See Quarto issue linked below for details. 

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/7058

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [ ] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [ ] If relevant, a temporary fix has been implemented. 
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [ ] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

### Issue Details

See Quarto issue linked below for details. 

### Links to related Quarto Issues, Pull Requests, Commits, etc.

- Quarto issue: https://github.com/quarto-dev/quarto-cli/issues/7058

### Status Checklist

- [x] Identified issue depends on a Quarto dependency and added to the tracker here. 
- [x] Issue filed with Quarto via their GitHub. (Add relevant links above.)
- [ ] The issue has been fixed on the Quarto side. (Add relevant links above.)
- [ ] If relevant, a temporary fix has been implemented. 
- [ ] The fix has been included in a Quarto release or pre-release. 
- [ ] The JEDI website was tested with the newer Quarto release or pre-release. 
- [ ] We have updated the JEDI website to a newer Quarto release and the issue is now addressed. 
- [ ] Any remaining related cleanup tasks (e.g. removing temporary fixes that are no longer needed) have been completed. 

---

# Closed Issues

Please move any closed issues here.

**Comment by ravicodelabs** [comment]
We are retiring this aggregate issue tracker in favor of using individual issues. Below are a few additional notes:

- Issue Name: Twitter card description content is not being included in website HTML source
  - Since we are no longer using the embedded X/Twitter feed as of today, this is no longer relevant for us and can be closed. 
- Issue Name: Footer section bar missing
  - This has been fixed by Quarto and is available with Quarto v1.4.555. 
- Issue Name: Bootstrap variable for pagination color is getting overwrriten
  - This has been fixed by Quarto and is available with Quarto v1.4.555.
